apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  namespace: {{ .Values.namespace }}
data:
  init-user-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE gatewaydb;
        CREATE DATABASE celebrity_db;
        CREATE DATABASE fan_db;
        CREATE DATABASE ngo_db;
    EOSQL
