apiVersion: v1  
kind: Secret  
metadata:  
  name: secrets
type: Opaque  
data:  
  postgresql-password: cGFzc3dvcmQ=
  postgresql-user: cG9zdGdyZXM= 
  rabbitmq-password: bmVsbHk=
  rabbitmq_username: cGFzc3dvcmQ=